In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('E:\programming projects\\vgsales.csv')

df.describe()
df.columns
df

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\hp\AppData\Local\Temp\ipykernel_30856\1240722289.py:1: SyntaxWarning: invalid escape sequence '\p'
  df=pd.read_csv('E:\programming projects\\vgsales.csv')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [4]:
df_nintendo=df.loc[df['Publisher'] == 'Nintendo']
df_nintendo

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16269,16272,Slide Adventure: Mag Kid,DS,2007.0,Action,Nintendo,0.00,0.00,0.01,0.00,0.01
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01
16456,16459,Art Academy: Home Studio,WiiU,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01
16473,16476,Captain Rainbow,Wii,2008.0,Adventure,Nintendo,0.00,0.00,0.01,0.00,0.01
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01

In [5]:
df_nintsales=df_nintendo.Global_Sales.sum()
df_nintsales

1786.5600000000002

In [6]:
companies=df["Publisher"].drop_duplicates()
company_names=list(companies)
print(company_names)

['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive', 'Sony Computer Entertainment', 'Activision', 'Ubisoft', 'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft', 'Atari', '505 Games', 'Capcom', 'GT Interactive', 'Konami Digital Entertainment', 'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts', 'Virgin Interactive', 'Warner Bros. Interactive Entertainment', 'Universal Interactive', 'Eidos Interactive', 'RedOctane', 'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games', 'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive', 'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios', nan, 'Majesco Entertainment', 'Codemasters', 'Red Orb', 'Level 5', 'Arena Entertainment', 'Midway Games', 'JVC', 'Deep Silver', '989 Studios', 'NCSoft', 'UEP Systems', 'Parker Bros.', 'Maxis', 'Imagic', 'Tecmo Koei', 'Valve Software', 'ASCII Entertainment', 'Mindscape', 'Infogrames', 'Unknown', 'Square', 'Valve', 'Activision Value', 'Banpresto', 'D3Publisher', 'Oxygen Interactive', 'Red Storm Entertainment', 'Video System', 'Hello Games', 'Global Star', 'Gotham Games', 'Westwood Studios', 'GungHo', 'Crave Entertainment', 'Hudson Soft', 'Coleco', 'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games', 'Zoo Games', 'Accolade', 'Sony Online Entertainment', '3DO', 'RTL', 'Natsume', 'Focus Home Interactive', 'Alchemist', 'Black Label Games', 'SouthPeak Games', 'Mastertronic', 'Ocean', 'Zoo Digital Publishing', 'Psygnosis', 'City Interactive', 'Empire Interactive', 'Success', 'Compile', 'Russel', 'Taito', 'Agetec', 'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios', 'Tomy Corporation', 'Sammy Corporation', 'Koch Media', 'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki', 'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics', 'SCi', 'Quelle', 'mixi, Inc', 'Rage Software', 'Ubisoft Annecy', 'Scholastic Inc.', 'Interplay', 'Mystique', 'ChunSoft', 'Square EA', '20th Century Fox Video Games', 'Avanquest Software', 'Hudson Entertainment', 'Nordic Games', 'Men-A-Vision', 'Nobilis', 'Big Ben Interactive', 'Touchstone', 'Spike', 'Jester Interactive', 'Nippon Ichi Software', 'LEGO Media', 'Quest', 'Illusion Softworks', 'Tigervision', 'Funbox Media', 'Rocket Company', 'Metro 3D', 'Mattel Interactive', 'IE Institute', 'Rondomedia', 'Sony Computer Entertainment America', 'Universal Gamex', 'Ghostlight', 'Wizard Video Games', 'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna', 'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer', 'Enterbrain', 'Xseed Games', 'Imagineer', 'System 3 Arcade Software', 'CPG Products', 'Aruze Corp', 'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco', 'Answer Software', 'XS Games', 'Activision Blizzard', 'Pack In Soft', 'Rebellion', 'Xplosiv', 'Ultravision', 'GameMill Entertainment', 'Wanadoo', 'NovaLogic', 'Telltale Games', 'Epoch', 'BAM! Entertainment', 'Knowledge Adventure', 'Mastiff', 'Tetris Online', 'Harmonix Music Systems', 'ESP', 'TYO', 'Telegames', 'Mud Duck Productions', 'Screenlife', 'Pioneer LDC', 'Magical Company', 'Mentor Interactive', 'Kemco', 'Human Entertainment', 'Avanquest', 'Data Age', 'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games', '989 Sports', 'Takara Tomy', 'Media Rings', 'Elf', 'Kalypso Media', 'Starfish', 'Zushi Games', 'Jorudan', 'Destination Software, Inc', 'New', 'Brash Entertainment', 'ITT Family Games', 'PopCap Games', 'Home Entertainment Suppliers', 'Ackkstudios', 'Starpath Corp.', 'P2 Games', 'BPS', 'Gathering of Developers', 'NewKidCo', 'Storm City Games', 'CokeM Interactive', 'CBS Electronics', 'Magix', 'Marvelous Interactive', 'Nihon Falcom Corporation', 'Wargaming.net', 'Angel Studios', 'Arc System Works', 'Playmates', 'SNK Playmore', 'Hamster Corporation', 'From Software', 'Nippon Columbia', 'Nichibutsu', 'Little Orbit', 'Conspiracy Entertainment', 'DTP Entertainment', 'Hect', 'Mumbo Jumbo', 'Pacific Century Cyber Works', 'Indie Games', 'Liquid Games', 'NEC', 'Axela', 'ArtDink', 'Sunsoft', 'Gust', 'SNK', 'NEC Interchannel', 'FuRyu', 'Xing Entertainment', 'ValuSoft', 'Victor Interactive', 'Detn8 Games', 'American Softworks', 'Nordcurrent', 'Bomb', 'Falcom Corporation', 'AQ Interactive', 'CCP', 'Milestone S.r.l.', 'Sears', 'JoWood Productions', 'Seta Corporation', 'On Demand', 'NCS', 'Aspyr', 'Gremlin Interactive Ltd', 'Agatsuma Entertainment', 'Compile Heart', 'Culture Brain', 'Mad Catz', 'Shogakukan', 'Merscom LLC', 'Rebellion Developments', 'Nippon Telenet', 'TDK Core', 'bitComposer Games', 'Foreign Media Games', 'Astragon', 'SSI', 'Kadokawa Games', 'Idea Factory', 'Performance Designed Products', 'Asylum Entertainment', 'Core Design Ltd.', 'PlayV', 'UFO Interactive', 'Idea Factory International', 'Playlogic Game Factory', 'Essential Games', 'Adeline Software', 'Funcom', 'Panther Software', 'Blast! Entertainment Ltd', 'Game Life', 'DSI Games', 'Avalon Interactive', 'Popcorn Arcade', 'Neko Entertainment', 'Vir2L Studios', 'Aques', 'Syscom', 'White Park Bay Software', 'System 3', 'Vatical Entertainment', 'Daedalic', 'EA Games', 'Media Factory', 'Vic Tokai', 'The Adventure Company', 'Game Arts', 'Broccoli', 'Acquire', 'General Entertainment', 'Excalibur Publishing', 'Imadio', 'Swing! Entertainment', 'Sony Music Entertainment', 'Aqua Plus', 'Paradox Interactive', 'Hip Interactive', 'DreamCatcher Interactive', 'Tripwire Interactive', 'Sting', 'Yacht Club Games', 'SCS Software', 'Bigben Interactive', 'Havas Interactive', 'Slitherine Software', 'Graffiti', 'Funsta', 'Telstar', 'U.S. Gold', 'DreamWorks Interactive', 'Data Design Interactive', 'MTO', 'DHM Interactive', 'FunSoft', 'SPS', 'Bohemia Interactive', 'Reef Entertainment', 'Tru Blu Entertainment', 'Moss', 'T&E Soft', 'O-Games', 'Aksys Games', 'NDA Productions', 'Data East', 'Time Warner Interactive', 'Gainax Network Systems', 'Daito', 'O3 Entertainment', 'Gameloft', 'Xicat Interactive', 'Simon & Schuster Interactive', 'Valcon Games', 'PopTop Software', 'TOHO', 'HMH Interactive', '5pb', 'Cave', 'CDV Software Entertainment', 'Microids', 'PM Studios', 'Paon', 'Micro Cabin', 'GameTek', 'Benesse', 'Type-Moon', 'Enjoy Gaming ltd.', 'Asmik Corp', 'Interplay Productions', 'Asmik Ace Entertainment', 'inXile Entertainment', 'Image Epoch', 'Phantom EFX', 'Evolved Games', 'responDESIGN', 'Culture Publishers', 'Griffin International', 'Hackberry', 'Hearty Robin', 'Nippon Amuse', 'Origin Systems', 'Seventh Chord', 'Mitsui', 'Milestone', 'Abylight', 'Flight-Plan', 'Glams', 'Locus', 'Warp', 'Daedalic Entertainment', 'Alternative Software', 'Myelin Media', 'Mercury Games', 'Irem Software Engineering', 'Sunrise Interactive', 'Elite', 'Evolution Games', 'Tivola', 'Global A Entertainment', 'Edia', 'Athena', 'Aria', 'Gamecock', 'Tommo', 'Altron', 'Happinet', 'iWin', 'Media Works', 'Fortyfive', 'Revolution Software', 'Imax', 'Crimson Cow', '10TACLE Studios', 'Groove Games', 'Pack-In-Video', 'Insomniac Games', 'Ascaron Entertainment GmbH', 'Asgard', 'Ecole', 'Yumedia', 'Phenomedia', 'HAL Laboratory', 'Grand Prix Games', 'DigiCube', 'Creative Core', 'Kaga Create', 'WayForward Technologies', 'LSP Games', 'ASCII Media Works', 'Coconuts Japan', 'Arika', 'Ertain', 'Marvel Entertainment', 'Prototype', 'TopWare Interactive', 'Phantagram', '1C Company', 'The Learning Company', 'TechnoSoft', 'Vap', 'Misawa', 'Tradewest', 'Team17 Software', 'Yeti', 'Pow', 'Navarre Corp', 'MediaQuest', 'Max Five', 'Comfort', 'Monte Christo Multimedia', 'Pony Canyon', 'Riverhillsoft', 'Summitsoft', 'Milestone S.r.l', 'Playmore', 'MLB.com', 'Kool Kizz', 'Flashpoint Games', '49Games', 'Legacy Interactive', 'Alawar Entertainment', 'CyberFront', 'Cloud Imperium Games Corporation', 'Societa', 'Virtual Play Games', 'Interchannel', 'Sonnet', 'Experience Inc.', 'Zenrin', 'Iceberg Interactive', 'Ivolgamus', '2D Boy', 'MC2 Entertainment', 'Kando Games', 'Just Flight', 'Office Create', 'Mamba Games', 'Fields', 'Princess Soft', 'Maximum Family Games', 'Berkeley', 'Fuji', 'Dusenberry Martin Racing', 'imageepoch Inc.', 'Big Fish Games', 'Her Interactive', 'Kamui', 'ASK', 'Headup Games', 'KSS', 'Cygames', 'KID', 'Quinrose', 'Sunflowers', 'dramatic create', 'TGL', 'Encore', 'Extreme Entertainment Group', 'Intergrow', 'G.Rev', 'Sweets', 'Kokopeli Digital Studios', 'Number None', 'Nexon', 'id Software', 'BushiRoad', 'Tryfirst', 'Strategy First', '7G//AMES', 'GN Software', "Yuke's", 'Easy Interactive', 'Licensed 4U', 'FuRyu Corporation', 'Lexicon Entertainment', 'Paon Corporation', 'Kids Station', 'GOA', 'Graphsim Entertainment', 'King Records', 'Introversion Software', 'Minato Station', 'Devolver Digital', 'Blue Byte', 'Gaga', 'Yamasa Entertainment', 'Plenty', 'Views', 'fonfun', 'NetRevo', 'Codemasters Online', 'Quintet', 'Phoenix Games', 'Dorart', 'Marvelous Games', 'Focus Multimedia', 'Imageworks', 'Karin Entertainment', 'Aerosoft', 'Technos Japan Corporation', 'Gakken', 'Mirai Shounen', 'Datam Polystar', 'Saurus', 'HuneX', 'Revolution (Japan)', 'Giza10', 'Visco', 'Alvion', 'Mycom', 'Giga', 'Warashi', 'System Soft', 'Sold Out', 'Lighthouse Interactive', 'Masque Publishing', 'RED Entertainment', 'Michaelsoft', 'Media Entertainment', 'New World Computing', 'Genterprise', 'Interworks Unlimited, Inc.', 'Boost On', 'Stainless Games', 'EON Digital Entertainment', 'Epic Games', 'Naxat Soft', 'Ascaron Entertainment', 'Piacci', 'Nitroplus', 'Paradox Development', 'Otomate', 'Ongakukan', 'Commseed', 'Inti Creates', 'Takuyo', 'Interchannel-Holon', 'Rain Games', 'UIG Entertainment']

In [7]:



# def sales_total():
d = []
for loop in company_names:
    df_test = df.loc[df['Publisher'] == loop]
    numbers = df_test.Global_Sales.sum()
    d.append(
        {'companies': loop, 'total_sales': numbers}
    )

df1 = pd.DataFrame(d)
    
    
nan_values=  df1[df1.isna().any(axis=1)]
df1.dropna(how='any',inplace=True)
df1.reset_index(drop=True,inplace=True)
    
df1

                       companies  total_sales
0                       Nintendo      1786.56
1         Microsoft Game Studios       245.79
2           Take-Two Interactive       399.54
3    Sony Computer Entertainment       607.50
4                     Activision       727.46
..                           ...          ...
573                 Inti Creates         0.01
574                       Takuyo         0.01
575           Interchannel-Holon         0.01
576                   Rain Games         0.01
577            UIG Entertainment         0.01

[578 rows x 2 columns]

In [8]:

df1=df1.sort_values('total_sales',ascending=False)
df1

                       companies  total_sales
0                       Nintendo      1786.56
7                Electronic Arts      1110.32
4                     Activision       727.46
3    Sony Computer Entertainment       607.50
5                        Ubisoft       474.72
..                           ...          ...
559                  Genterprise         0.01
558          New World Computing         0.01
557          Media Entertainment         0.01
556                  Michaelsoft         0.01
577            UIG Entertainment         0.01

[578 rows x 2 columns]